# Yaml file for satellite config

satellites:
  - robot_id: 0
    pos_cov_init: 1
    vel_cov_init: 0.1
    dim: 6
    meas_dim: 4
    R_weight: 10e-5
    N: N
    n_sats: 2
    landmarks: landmark_objects
    orbital_elements: {e: 0.1, a: 7478.0, i: 90.0, omega_dot: 0.0, omega: 90.0, M: 0.0} # [e, a, i, Omega, omega, M]
    camera_exists: True

  - robot_id: 1
    pos_cov_init: 1
    vel_cov_init: 0.1
    dim: 6
    meas_dim: 4
    R_weight: 10e-5
    N: N
    n_sats: 2
    landmarks: landmark_objects
    orbital_elements: {e: 0.1, a: 7478.0, i: 90.0, omega_dot: 90.0, omega: 45.0, M: 0.0} # [e, a, i, Omega, omega, M]
    camera_exists: True
  
  - robot_id: 2
    pos_cov_init: 1
    vel_cov_init: 0.1
    dim: 6
    meas_dim: 4
    R_weight: 10e-5
    N: N
    n_sats: 2
    landmarks: landmark_objects
    orbital_elements: {e: 0.1, a: 7478.0, i: 85.0, omega_dot: 270.0, omega: 60.0, M: 0.0} # [e, a, i, Omega, omega, M]
    camera_exists: True

  # - robot_id: 3
  #   state: [0,-6928,0,0,0,-7.585163531693988]
  #   pos_cov_init: 1
  #   vel_cov_init: 0.1
  #   dim: 6
  #   meas_dim: 5
  #   R_weight: 0.25
  #   N: N
  #   n_sats: 2
  #   landmarks: landmark_objects
  #   inclination: 0.0 # define in degrees!
  #   camera_exists: True
