# Yaml file for satellite config

satellites:
  - robot_id: 0
    pos_cov_init: 10
    vel_cov_init: 1
    dim: 6
    R_weight_range: 1e-5
    R_weight_land_bearing: 0.4
    R_weight_sat_bearing: 0.4
    landmarks: landmark_objects
    orbital_elements: {e: 0.0, a: 6928.0, i: 90.0, omega_dot: 0.0, omega: 0.0, M: 0.0} # [e, a, i, Omega, omega, M]
    camera_exists: True
    camera_fov: 60.0
    verbose: False
    ignore_earth: False


  - robot_id: 1
    pos_cov_init: 10
    vel_cov_init: 1
    dim: 6
    R_weight_range: 1e-5
    R_weight_land_bearing: 0.4
    R_weight_sat_bearing: 0.4
    landmarks: landmark_objects
    orbital_elements: {e: 0.05, a: 6928.0, i: 10.0, omega_dot: 0.0, omega: 0.0, M: 0.0} # [e, a, i, Omega, omega, M]
    camera_exists: True
    camera_fov: 60.0
    verbose: False
    ignore_earth: False


  - robot_id: 2
    pos_cov_init: 10
    vel_cov_init: 1
    dim: 6
    R_weight_range: 1e-5
    R_weight_land_bearing: 0.4
    R_weight_sat_bearing: 0.4
    landmarks: landmark_objects
    orbital_elements: {e: 0.05, a: 6928.0, i: 94.0, omega_dot: 0.0, omega: 0.0, M: 5.0} # [e, a, i, Omega, omega, M]
    camera_exists: True
    camera_fov: 60.0
    verbose: False
    ignore_earth: False


  - robot_id: 3
    pos_cov_init: 10
    vel_cov_init: 1
    dim: 6
    R_weight_range: 1e-5
    R_weight_land_bearing: 0.4
    R_weight_sat_bearing: 0.4
    landmarks: landmark_objects
    orbital_elements: {e: 0.0, a: 7000.0, i: 5.0, omega_dot: 0.0, omega: 2.0, M: 10.0} # [e, a, i, Omega, omega, M]
    camera_exists: True
    camera_fov: 60.0
    verbose: False
    ignore_earth: False


  - robot_id: 4
    pos_cov_init: 1
    vel_cov_init: 0.1
    dim: 6
    R_weight_range: 1e-5
    R_weight_land_bearing: 0.4
    R_weight_sat_bearing: 0.4
    landmarks: landmark_objects
    orbital_elements: {e: 0.1, a: 7478.0, i: 5.0, omega_dot: 25.0, omega: 20.0, M: 25.0} # [e, a, i, Omega, omega, M]
    camera_exists: True
    camera_fov: 60.0
    verbose: False
    ignore_earth: False
